#!/usr/bin/env python3
"""
Use Gemini to run a visual ranking analysis of the 3 before/after pairs.
"""
import os, json, base64, requests

GEMINI_KEY = ""
with open(os.path.expanduser("~/.openclaw/.env")) as f:
    for line in f:
        if line.startswith("GEMINI_API_KEY=") or line.startswith("GOOGLE_AI_API_KEY="):
            GEMINI_KEY = line.strip().split("=", 1)[1].strip('"').strip("'")

if not GEMINI_KEY:
    # Try GOOGLE_API_KEY
    with open(os.path.expanduser("~/.openclaw/.env")) as f:
        for line in f:
            if line.startswith("GOOGLE_API_KEY="):
                GEMINI_KEY = line.strip().split("=", 1)[1].strip('"').strip("'")

assert GEMINI_KEY, "Gemini API key not found"

MODEL = "gemini-2.5-flash"
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent?key={GEMINI_KEY}"

IMG_DIR = "assets/images/lead-magnet"

def load_image_b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()

# Build the request with all 6 images
parts = []

parts.append({"text": """You are a professional visual design critic and marketing conversion expert. 

I have 3 before/after image pairs. Each pair shows the SAME subject generated by the SAME AI model with the SAME settings — the ONLY difference is the prompt quality.

- BEFORE = generic, lazy prompt (what a regular person types)
- AFTER = skill-optimized prompt (with cinematic direction, lighting specs, composition, mood)

For each pair, analyze:
1. **Visual Quality Gap** (1-10): How dramatic is the difference between before and after?
2. **Instant Readability** (1-10): Can a non-expert see the difference in under 2 seconds?
3. **Emotional Impact** (1-10): Does the "after" image create a feeling the "before" doesn't?
4. **Commercial Relevance** (1-10): Would an agency immediately see this as useful for client work?
5. **Composition & Lighting**: What specific techniques in the "after" make it superior?

Then provide a FINAL RANKING of the 3 pairs from best to worst for use as a before/after comparison on a website selling a prompt engineering toolkit to creative agencies.

Explain what makes the winner the winner in concrete visual terms.

Here are the 6 images:

PAIR 1: PORTRAIT
Before prompt: "portrait of an old man"
After prompt: Rembrandt lighting, shallow DOF f/1.8, skin pores, catchlights, medium format, emotional

PAIR 1 BEFORE:"""})

parts.append({"inline_data": {"mime_type": "image/jpeg", "data": load_image_b64(f"{IMG_DIR}/before-portrait.jpg")}})
parts.append({"text": "PAIR 1 AFTER:"})
parts.append({"inline_data": {"mime_type": "image/jpeg", "data": load_image_b64(f"{IMG_DIR}/after-portrait.jpg")}})

parts.append({"text": """
PAIR 2: FOOD
Before prompt: "a plate of pasta"
After prompt: Hand-rolled tagliatelle, beef ragu, steam, dramatic side-lighting, 100mm macro, dark moody, Michelin-star

PAIR 2 BEFORE:"""})
parts.append({"inline_data": {"mime_type": "image/jpeg", "data": load_image_b64(f"{IMG_DIR}/before-food.jpg")}})
parts.append({"text": "PAIR 2 AFTER:"})
parts.append({"inline_data": {"mime_type": "image/jpeg", "data": load_image_b64(f"{IMG_DIR}/after-food.jpg")}})

parts.append({"text": """
PAIR 3: INTERIOR
Before prompt: "modern living room"
After prompt: Architect-designed loft, golden hour light beams, dust particles, Eames chair, concrete floors, 24mm wide-angle, lived-in

PAIR 3 BEFORE:"""})
parts.append({"inline_data": {"mime_type": "image/jpeg", "data": load_image_b64(f"{IMG_DIR}/before-interior.jpg")}})
parts.append({"text": "PAIR 3 AFTER:"})
parts.append({"inline_data": {"mime_type": "image/jpeg", "data": load_image_b64(f"{IMG_DIR}/after-interior.jpg")}})

parts.append({"text": "\n\nNow provide your full analysis and ranking."})

payload = {
    "contents": [{"parts": parts}],
    "generationConfig": {
        "temperature": 0.4,
        "maxOutputTokens": 4000,
    }
}

print("⏳ Sending 6 images to Gemini for visual analysis...")
r = requests.post(API_URL, json=payload, timeout=120)
r.raise_for_status()
data = r.json()

text = data["candidates"][0]["content"]["parts"][0]["text"]
print("\n" + "=" * 70)
print("GEMINI VISUAL RANKING ANALYSIS")
print("=" * 70)
print(text)

# Save analysis
with open(f"{IMG_DIR}/gemini-analysis.md", "w") as f:
    f.write("# Gemini Visual Ranking Analysis\n\n")
    f.write(f"Model: {MODEL}\n\n")
    f.write(text)
print(f"\n✅ Saved to {IMG_DIR}/gemini-analysis.md")
